lib/producthunt_elixir_web/router.ex
defmodule ProducthuntElixirWeb.Router do
  use ProducthuntElixirWeb, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser
    coherence_routes()
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", ProducthuntElixirWeb do
    pipe_through :browser  # Use the default browser stack

    get "/", ProductController, :index
    resources "/products", ProductController
  end

  scope "/", ProducthuntElixirWeb do
    pipe_through :protected
    # Add protected routes below
  end

  # Other scopes may use custom stacks.
  # scope "/api", ProducthuntElixirWeb do
  #   pipe_through :api
  # end
end

lib/producthunt_elixir_web/views/coherence/layout_view.ex
defmodule ProducthuntElixirWeb.Coherence.LayoutView do
  use ProducthuntElixirWeb.Coherence, :view
end

lib/producthunt_elixir_web/views/layout_view.ex
defmodule ProducthuntElixirWeb.LayoutView do
  use ProducthuntElixirWeb, :view
end

lib/producthunt_elixir_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Product Hunt is a curation of the best new products, every day. Discover the latest mobile apps, websites, and technology products that everyone's talking about.">
    <link rel="shortcut icon" href="<%= static_path(@conn, "/images/favicon.ico") %>">

    <title>Product Hunt</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-faded">
      <div class="container">
        <a class="navbar-brand" href="/">
          <svg width="32" height="32" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="M40 20c0 11.046-8.954 20-20 20S0 31.046 0 20 8.954 0 20 0s20 8.954 20 20" fill="#DA552F"></path><path d="M22.667 20H17v-6h5.667c1.656 0 3 1.343 3 3s-1.344 3-3 3m0-10H13v20h4v-6h5.667c3.866 0 7-3.134 7-7s-3.134-7-7-7" fill="#FFF"></path></g></svg>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <% css_class = if Application.get_env(:producthunt_elixir, :env) != :test do
                         " collapse"
                       else
                         ""
                       end %>
        <div id="navbarNavDropdown" class="navbar-collapse<%= css_class %>">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <ul class="navbar-nav">
            <%= if Coherence.current_user(@conn) do %>
              <%= if @conn.assigns[:remembered] do %>
                <li style="color: red;">!!</li>
              <% end %>
            <% end %>

            <%= if Coherence.current_user(@conn) do %>
              <li class="nav-item">
                <%= link to: product_path(@conn, :new), class: "nav-link", title: dgettext("producthunt", "Register product") do %>
                  <i class="fa fa-plus" aria-hidden="true"></i>
                <% end %>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= Coherence.current_user_name(@conn) %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#"><%= dgettext("producthunt", "My profile") %></a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#"><%= dgettext("producthunt", "Settings") %></a>
                  <div class="dropdown-divider"></div>
                  <%= ProducthuntElixirWeb.Coherence.ViewHelpers.signout_link(@conn, dgettext("coherence", "Sign Out"), "dropdown-item") %>
                </div>
              </li>
            <% end %>

            <%= ProducthuntElixirWeb.Coherence.ViewHelpers.coherence_links(@conn, :layout, signout_class: nil, signout: nil, signin: dgettext("coherence", "Login"), register: dgettext("coherence", "Sign up")) %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <main role="main" class="py-md-3">
        <%
        info = get_flash(@conn, :info)
        error = get_flash(@conn, :error)
        %>
        <%= if info do %>
          <div class="alert alert-info" role="alert"><%= info %></div>
        <% end %>
        <%= if error do %>
          <div class="alert alert-danger" role="alert"><%= error %></div>
        <% end %>

        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>